
app = "albion-counter"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 10000
  auto_stop_machines = false
  auto_start_machines = true
  force_https = true
  min_machines_running = 1
